name: ci

on:
  push:
    # branches:
    #   - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:client'
          push: true
          tags: dkarter/multi-docker-client:latest

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:client'
          push: true
          tags: dkarter/multi-docker-server:latest

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:worker'
          push: true
          tags: dkarter/multi-docker-worker:latest

      - name: Build and push router
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:nginx'
          push: true
          tags: dkarter/multi-docker-router:latest
