name: ci

on:
  push:
    # branches:
    #   - 'master'

jobs:
  docker-build-push:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Client Image Meta
        id: clientMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/multi-docker-client
          tags: |
            latest
            type=sha

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:client'
          push: true
          tags: ${{ steps.clientMeta.outputs.tags }}

      - name: Server Image Meta
        id: serverMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/multi-docker-server
          tags: |
            latest
            type=sha

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:server'
          push: true
          tags: ${{ steps.serverMeta.outputs.tags }}

      - name: Worker Image Meta
        id: workerMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/multi-docker-worker
          tags: |
            latest
            type=sha

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:worker'
          push: true
          tags: ${{ steps.workerMeta.outputs.tags }}

  deploy:
    name: Deploy Apps To K8s on Google Cloud
    runs-on: ubuntu-latest
    needs: docker-build-push

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set Identity Provider
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: 'projects/252624727660/locations/global/workloadIdentityPools/multi-cluster-id-pool/providers/oidc'
          service_account: 'gh-deployer@multi-k8s-349605.iam.gserviceaccount.com'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-349605

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=dkarter/multi-docker-server:sha-${{ env.SHA }}
          kubectl set image deployments/client-deployment client=dkarter/multi-docker-client:sha-${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=dkarter/multi-docker-worker:sha-${{ env.SHA }}
