name: ci

on:
  push:
    # branches:
    #   - 'master'

jobs:
  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Client Image Meta
        id: clientMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/multi-docker-client
          tags: |
            latest
            type=sha

      - name: Build and push client
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:client'
          push: true
          tags: ${{ steps.clientMeta.outputs.tags }}

      - name: Server Image Meta
        id: serverMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/multi-docker-server
          tags: |
            latest
            type=sha

      - name: Build and push server
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:server'
          push: true
          tags: ${{ steps.serverMeta.outputs.tags }}

      - name: Worker Image Meta
        id: workerMeta
        uses: docker/metadata-action@v4
        with:
          images: dkarter/multi-docker-worker
          tags: |
            latest
            type=sha

      - name: Build and push worker
        uses: docker/build-push-action@v2
        with:
          context: '{{defaultContext}}:worker'
          push: true
          tags: ${{ steps.workerMeta.outputs.tags }}
